site_name: OpenControl
repo_url: https://github.com/opencontrol/opencontrol-website/
google_analytics: ['UA-69554101-1', 'opencontrol.github.io']
remote_branch: master
pages:
  - Intro: 'index.md'
  - FAQ: 'faq.md'
  - Schema: 'schema.md'
  - Pipeline: 'pipelines.md'
  - Members: 'members.md'
